[package]
name = "apheleia-ecs"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
apheleia-core.workspace = true

smallvec.workspace = true
num-traits.workspace = true
tree-ds.workspace = true
sparseset.workspace = true
rustc-hash.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
indexmap.workspace = true
