[workspace]
resolver = "2"
members = ["crates/*", "examples/*",  "tests/*" ]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
apheleia-types = { path = "crates/apheleia-types" }
apheleia-core = { path = "crates/apheleia-core" }
apheleia-ui = { path = "crates/apheleia-ui" }
apheleia-app = { path = "crates/apheleia-app" }
apheleia-app-new = { path = "crates/apheleia-app-new" }
apheleia-ecs = { path = "crates/apheleia-ecs" }
apheleia-ecs-new = { path = "crates/apheleia-ecs-new" }
apheleia-widgets = { path = "crates/apheleia-widgets" }

smallvec = "1.15.1"
sparseset = "1.0.1"
crossterm = "0.29.0"
indexmap = "2.2.2"
tree-ds = "0.2.0"
rustc-hash = "2.1.2"
log = { version = "0.4", features = ["release_max_level_off"] }
fern = "0.7"
chrono = "0.4"
num-traits = "0.2.19"
