[workspace]
resolver = "2"
members = [ "crates/*", "examples/*",  "tests/*" ]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
apheleia-types = { path = "crates/apheleia-types" }
apheleia-core = { path = "crates/apheleia-core" }
apheleia-ui = { path = "crates/apheleia-ui" }
apheleia-app = { path = "crates/apheleia-app" }
apheleia-ecs = { path = "crates/apheleia-ecs" }
apheleia-macros = { path = "crates/apheleia-macros" }
apheleia-widgets = { path = "crates/apheleia-widgets" }
apheleia = { path = "crates/apheleia" }

crossterm = "0.29.0"
indexmap = "2.2.2"
tree-ds = "0.2.0"
rustc-hash = "2.1.2"
log = "0.4"
fern = "0.7"
chrono = "0.4"
