[package]
name = "apheleia-ui"
version.workspace = true
edition.workspace = true

[dependencies]
apheleia-core.workspace = true

indexmap.workspace = true
crossterm.workspace = true
tree-ds.workspace = true
rustc-hash.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
