[package]
name = "rewrite-test"
version.workspace = true
edition.workspace = true

[dependencies]
crossterm.workspace = true
apheleia-core.workspace = true
apheleia-app.workspace = true
apheleia-ecs.workspace = true
apheleia-widgets.workspace = true

log.workspace = true
fern.workspace = true
chrono.workspace = true

